# Generated by Django 4.2 on 2023-04-08 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0004_remove_product_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutBound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_bound_quantity', models.PositiveIntegerField()),
                ('out_bound_created_at', models.DateTimeField(auto_now_add=True)),
                ('out_bound_price', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
            options={
                'db_table': 'out_bound',
            },
        ),
    ]
