# Generated by Django 4.2 on 2023-04-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invetory',
            new_name='Inventory',
        ),
    ]
