# Generated by Django 4.2 on 2023-04-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total',
        ),
    ]
